### ISSUE TITLE
Regression in Unit Tests

### ISSUE THREAD

**Issue by katiesweet** [michaelkamerath/SharedServer#64]
@michaelkamerath @droidkfx @C-Merrill 
The server builds fine, but my team's unit tests fail. I assume this is due to the TCPConnection::create(service) that was modified in these tests? Does anyone know the reason why it is of the top of their head? I tried closing the TCP Connection manually (thinking that might be the issue) but it didn't work. I can look into into it more if needed.

![screen shot 2016-11-29 at 2 36 31 pm](https://cloud.githubusercontent.com/assets/16142858/20729976/87cdacaa-b641-11e6-95f0-634b4445b9ea.png)

![screen shot 2016-11-29 at 2 17 02 pm](https://cloud.githubusercontent.com/assets/16142858/20729437/324ecab8-b63f-11e6-831e-f43d476542fb.png)

**Comment by droidkfx** [comment]
This is why : 

https://github.com/michaelkamerath/SharedServer/blob/15fa8664d59d10d64a13d73936ac88836ca4eefe/source/PlayerAPI/Player.cpp#L24

Which since you are creating a player with no socket connection causes the `remote_endpoint()` to throw the error since it has no remote endpoint. Surrounding the whole thing with a try catch should fix it.

**Comment by droidkfx** [comment]
I will change this and push up later tonight along with the Linux fixes

**Comment by katiesweet** [comment]
Thanks @droidkfx!

**Comment by mikamerath** [comment]
Pull Request: https://github.com/michaelkamerath/SharedServer/pull/54
